; Auto-generated. Do not edit!


(cl:in-package sr_grasp_msgs-msg)


;//! \htmlinclude ForceControlResult.msg.html

(cl:defclass <ForceControlResult> (roslisp-msg-protocol:ros-message)
  ((outcome
    :reader outcome
    :initarg :outcome
    :type cl:fixnum
    :initform 0))
)

(cl:defclass ForceControlResult (<ForceControlResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ForceControlResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ForceControlResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sr_grasp_msgs-msg:<ForceControlResult> is deprecated: use sr_grasp_msgs-msg:ForceControlResult instead.")))

(cl:ensure-generic-function 'outcome-val :lambda-list '(m))
(cl:defmethod outcome-val ((m <ForceControlResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sr_grasp_msgs-msg:outcome-val is deprecated.  Use sr_grasp_msgs-msg:outcome instead.")
  (outcome m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ForceControlResult>) ostream)
  "Serializes a message object of type '<ForceControlResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'outcome)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ForceControlResult>) istream)
  "Deserializes a message object of type '<ForceControlResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'outcome)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ForceControlResult>)))
  "Returns string type for a message object of type '<ForceControlResult>"
  "sr_grasp_msgs/ForceControlResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ForceControlResult)))
  "Returns string type for a message object of type 'ForceControlResult"
  "sr_grasp_msgs/ForceControlResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ForceControlResult>)))
  "Returns md5sum for a message object of type '<ForceControlResult>"
  "27ec091ad476af1fa779efed25089b50")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ForceControlResult)))
  "Returns md5sum for a message object of type 'ForceControlResult"
  "27ec091ad476af1fa779efed25089b50")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ForceControlResult>)))
  "Returns full string definition for message of type '<ForceControlResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%uint8 outcome~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ForceControlResult)))
  "Returns full string definition for message of type 'ForceControlResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%uint8 outcome~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ForceControlResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ForceControlResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ForceControlResult
    (cl:cons ':outcome (outcome msg))
))
