; Auto-generated. Do not edit!


(cl:in-package sr_grasp_msgs-msg)


;//! \htmlinclude GraspManualFeedback.msg.html

(cl:defclass <GraspManualFeedback> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:fixnum
    :initform 0))
)

(cl:defclass GraspManualFeedback (<GraspManualFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspManualFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspManualFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sr_grasp_msgs-msg:<GraspManualFeedback> is deprecated: use sr_grasp_msgs-msg:GraspManualFeedback instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <GraspManualFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sr_grasp_msgs-msg:state-val is deprecated.  Use sr_grasp_msgs-msg:state instead.")
  (state m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<GraspManualFeedback>)))
    "Constants for message type '<GraspManualFeedback>"
  '((:SEARCHING . 0)
    (:SELECTING . 1)
    (:GRABBING . 2)
    (:RELEASING . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'GraspManualFeedback)))
    "Constants for message type 'GraspManualFeedback"
  '((:SEARCHING . 0)
    (:SELECTING . 1)
    (:GRABBING . 2)
    (:RELEASING . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspManualFeedback>) ostream)
  "Serializes a message object of type '<GraspManualFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspManualFeedback>) istream)
  "Deserializes a message object of type '<GraspManualFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspManualFeedback>)))
  "Returns string type for a message object of type '<GraspManualFeedback>"
  "sr_grasp_msgs/GraspManualFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspManualFeedback)))
  "Returns string type for a message object of type 'GraspManualFeedback"
  "sr_grasp_msgs/GraspManualFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspManualFeedback>)))
  "Returns md5sum for a message object of type '<GraspManualFeedback>"
  "a975d832f370307d65c54c1449117d0d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspManualFeedback)))
  "Returns md5sum for a message object of type 'GraspManualFeedback"
  "a975d832f370307d65c54c1449117d0d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspManualFeedback>)))
  "Returns full string definition for message of type '<GraspManualFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%# State shows what the node is currently doing.~%uint8 SEARCHING=0~%uint8 SELECTING=1~%uint8 GRABBING=2~%uint8 RELEASING=3~%uint8 state~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspManualFeedback)))
  "Returns full string definition for message of type 'GraspManualFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%# State shows what the node is currently doing.~%uint8 SEARCHING=0~%uint8 SELECTING=1~%uint8 GRABBING=2~%uint8 RELEASING=3~%uint8 state~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspManualFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspManualFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspManualFeedback
    (cl:cons ':state (state msg))
))
