; Auto-generated. Do not edit!


(cl:in-package sr_grasp_msgs-msg)


;//! \htmlinclude GraspManualGoal.msg.html

(cl:defclass <GraspManualGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspManualGoal (<GraspManualGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspManualGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspManualGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sr_grasp_msgs-msg:<GraspManualGoal> is deprecated: use sr_grasp_msgs-msg:GraspManualGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspManualGoal>) ostream)
  "Serializes a message object of type '<GraspManualGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspManualGoal>) istream)
  "Deserializes a message object of type '<GraspManualGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspManualGoal>)))
  "Returns string type for a message object of type '<GraspManualGoal>"
  "sr_grasp_msgs/GraspManualGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspManualGoal)))
  "Returns string type for a message object of type 'GraspManualGoal"
  "sr_grasp_msgs/GraspManualGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspManualGoal>)))
  "Returns md5sum for a message object of type '<GraspManualGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspManualGoal)))
  "Returns md5sum for a message object of type 'GraspManualGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspManualGoal>)))
  "Returns full string definition for message of type '<GraspManualGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Action for a user to grasp an object.~%# Implimented by sr_grasp_demo.~%# Send the Goal, the server will find objects in the scene, display them in~%# rviz and wait for you to select one. When you do sr_grasp_object is told to~%# grasp that object.~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspManualGoal)))
  "Returns full string definition for message of type 'GraspManualGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Action for a user to grasp an object.~%# Implimented by sr_grasp_demo.~%# Send the Goal, the server will find objects in the scene, display them in~%# rviz and wait for you to select one. When you do sr_grasp_object is told to~%# grasp that object.~%# Goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspManualGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspManualGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspManualGoal
))
