; Auto-generated. Do not edit!


(cl:in-package sr_grasp_msgs-msg)


;//! \htmlinclude GraspManualResult.msg.html

(cl:defclass <GraspManualResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspManualResult (<GraspManualResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspManualResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspManualResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sr_grasp_msgs-msg:<GraspManualResult> is deprecated: use sr_grasp_msgs-msg:GraspManualResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspManualResult>) ostream)
  "Serializes a message object of type '<GraspManualResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspManualResult>) istream)
  "Deserializes a message object of type '<GraspManualResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspManualResult>)))
  "Returns string type for a message object of type '<GraspManualResult>"
  "sr_grasp_msgs/GraspManualResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspManualResult)))
  "Returns string type for a message object of type 'GraspManualResult"
  "sr_grasp_msgs/GraspManualResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspManualResult>)))
  "Returns md5sum for a message object of type '<GraspManualResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspManualResult)))
  "Returns md5sum for a message object of type 'GraspManualResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspManualResult>)))
  "Returns full string definition for message of type '<GraspManualResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspManualResult)))
  "Returns full string definition for message of type 'GraspManualResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspManualResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspManualResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspManualResult
))
