; Auto-generated. Do not edit!


(cl:in-package sr_grasp_msgs-msg)


;//! \htmlinclude PlanGraspFeedback.msg.html

(cl:defclass <PlanGraspFeedback> (roslisp-msg-protocol:ros-message)
  ((number_of_synthesized_grasps
    :reader number_of_synthesized_grasps
    :initarg :number_of_synthesized_grasps
    :type cl:integer
    :initform 0))
)

(cl:defclass PlanGraspFeedback (<PlanGraspFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanGraspFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanGraspFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sr_grasp_msgs-msg:<PlanGraspFeedback> is deprecated: use sr_grasp_msgs-msg:PlanGraspFeedback instead.")))

(cl:ensure-generic-function 'number_of_synthesized_grasps-val :lambda-list '(m))
(cl:defmethod number_of_synthesized_grasps-val ((m <PlanGraspFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sr_grasp_msgs-msg:number_of_synthesized_grasps-val is deprecated.  Use sr_grasp_msgs-msg:number_of_synthesized_grasps instead.")
  (number_of_synthesized_grasps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanGraspFeedback>) ostream)
  "Serializes a message object of type '<PlanGraspFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'number_of_synthesized_grasps)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanGraspFeedback>) istream)
  "Deserializes a message object of type '<PlanGraspFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'number_of_synthesized_grasps) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanGraspFeedback>)))
  "Returns string type for a message object of type '<PlanGraspFeedback>"
  "sr_grasp_msgs/PlanGraspFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanGraspFeedback)))
  "Returns string type for a message object of type 'PlanGraspFeedback"
  "sr_grasp_msgs/PlanGraspFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanGraspFeedback>)))
  "Returns md5sum for a message object of type '<PlanGraspFeedback>"
  "5b5e246a46b8ebdce203ce200fc43d02")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanGraspFeedback)))
  "Returns md5sum for a message object of type 'PlanGraspFeedback"
  "5b5e246a46b8ebdce203ce200fc43d02")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanGraspFeedback>)))
  "Returns full string definition for message of type '<PlanGraspFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%# Number of grasps synthesized so far.~%int32 number_of_synthesized_grasps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanGraspFeedback)))
  "Returns full string definition for message of type 'PlanGraspFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%# Number of grasps synthesized so far.~%int32 number_of_synthesized_grasps~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanGraspFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanGraspFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanGraspFeedback
    (cl:cons ':number_of_synthesized_grasps (number_of_synthesized_grasps msg))
))
