// Generated by gencpp from file sr_grasp_msgs/AdjustGraspFeedback.msg
// DO NOT EDIT!


#ifndef SR_GRASP_MSGS_MESSAGE_ADJUSTGRASPFEEDBACK_H
#define SR_GRASP_MSGS_MESSAGE_ADJUSTGRASPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sr_grasp_msgs/KCL_GraspQuality.h>

namespace sr_grasp_msgs
{
template <class ContainerAllocator>
struct AdjustGraspFeedback_
{
  typedef AdjustGraspFeedback_<ContainerAllocator> Type;

  AdjustGraspFeedback_()
    : state(0)
    , quality()  {
    }
  AdjustGraspFeedback_(const ContainerAllocator& _alloc)
    : state(0)
    , quality(_alloc)  {
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef  ::sr_grasp_msgs::KCL_GraspQuality_<ContainerAllocator>  _quality_type;
  _quality_type quality;


    enum { SELECTING = 0u };
     enum { GAITING = 1u };
     enum { EXPLORING = 2u };
     enum { IMPROVING = 3u };
 

  typedef boost::shared_ptr< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AdjustGraspFeedback_

typedef ::sr_grasp_msgs::AdjustGraspFeedback_<std::allocator<void> > AdjustGraspFeedback;

typedef boost::shared_ptr< ::sr_grasp_msgs::AdjustGraspFeedback > AdjustGraspFeedbackPtr;
typedef boost::shared_ptr< ::sr_grasp_msgs::AdjustGraspFeedback const> AdjustGraspFeedbackConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sr_grasp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sr_grasp_msgs': ['/home/catheter/catheter_position/src/sr_grasp_msgs/msg', '/home/catheter/catheter_position/devel/share/sr_grasp_msgs/msg'], 'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/indigo/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f53e9a8ba34d5929c78e8792c960b05d";
  }

  static const char* value(const ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf53e9a8ba34d5929ULL;
  static const uint64_t static_value2 = 0xc78e8792c960b05dULL;
};

template<class ContainerAllocator>
struct DataType< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sr_grasp_msgs/AdjustGraspFeedback";
  }

  static const char* value(const ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Feedback\n\
# State shows what the node is currently doing.\n\
uint8 SELECTING=0\n\
uint8 GAITING=1\n\
uint8 EXPLORING=2\n\
uint8 IMPROVING=3\n\
uint8 state\n\
# A percentage or other measure of the quality of the grasp.\n\
KCL_GraspQuality quality\n\
\n\
\n\
================================================================================\n\
MSG: sr_grasp_msgs/KCL_GraspQuality\n\
# All 3D vectors are referenced in the fingertip core center\n\
\n\
Header header					# stamp\n\
geometry_msgs/Vector3 resultant_force  		# Resultant Force\n\
geometry_msgs/Vector3 resultant_torque      	# Resultant Torque\n\
float64[] hull_force_dist			# distances from force hull surface to origin in each octant\n\
float64[] hull_torque_dist			# distances from force hull surface to origin in each octant\n\
float64 hull_volume_force			# volume of force hull. basically the grasp quality. unitless.\n\
float64 hull_volume_torque			# volume of torque hull\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AdjustGraspFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sr_grasp_msgs::AdjustGraspFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "quality: ";
    s << std::endl;
    Printer< ::sr_grasp_msgs::KCL_GraspQuality_<ContainerAllocator> >::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SR_GRASP_MSGS_MESSAGE_ADJUSTGRASPFEEDBACK_H
