// Generated by gencpp from file sr_grasp_msgs/ForceControlGoal.msg
// DO NOT EDIT!


#ifndef SR_GRASP_MSGS_MESSAGE_FORCECONTROLGOAL_H
#define SR_GRASP_MSGS_MESSAGE_FORCECONTROLGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sr_grasp_msgs
{
template <class ContainerAllocator>
struct ForceControlGoal_
{
  typedef ForceControlGoal_<ContainerAllocator> Type;

  ForceControlGoal_()
    : set_point_upper(0.0)
    , set_point_lower(0.0)
    , start_degree(0.0)  {
    }
  ForceControlGoal_(const ContainerAllocator& _alloc)
    : set_point_upper(0.0)
    , set_point_lower(0.0)
    , start_degree(0.0)  {
    }



   typedef double _set_point_upper_type;
  _set_point_upper_type set_point_upper;

   typedef double _set_point_lower_type;
  _set_point_lower_type set_point_lower;

   typedef double _start_degree_type;
  _start_degree_type start_degree;




  typedef boost::shared_ptr< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ForceControlGoal_

typedef ::sr_grasp_msgs::ForceControlGoal_<std::allocator<void> > ForceControlGoal;

typedef boost::shared_ptr< ::sr_grasp_msgs::ForceControlGoal > ForceControlGoalPtr;
typedef boost::shared_ptr< ::sr_grasp_msgs::ForceControlGoal const> ForceControlGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sr_grasp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sr_grasp_msgs': ['/home/catheter/catheter_position/src/sr_grasp_msgs/msg', '/home/catheter/catheter_position/devel/share/sr_grasp_msgs/msg'], 'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'pcl_msgs': ['/opt/ros/indigo/share/pcl_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6aabfe1c6f601d99ee7099bd14184b9";
  }

  static const char* value(const ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6aabfe1c6f601d9ULL;
  static const uint64_t static_value2 = 0x9ee7099bd14184b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sr_grasp_msgs/ForceControlGoal";
  }

  static const char* value(const ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Force Control.\n\
# Goal\n\
float64 set_point_upper #reference normal force up\n\
float64 set_point_lower #reference normal force down\n\
float64 start_degree #start_degree at joint 3\n\
";
  }

  static const char* value(const ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.set_point_upper);
      stream.next(m.set_point_lower);
      stream.next(m.start_degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ForceControlGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sr_grasp_msgs::ForceControlGoal_<ContainerAllocator>& v)
  {
    s << indent << "set_point_upper: ";
    Printer<double>::stream(s, indent + "  ", v.set_point_upper);
    s << indent << "set_point_lower: ";
    Printer<double>::stream(s, indent + "  ", v.set_point_lower);
    s << indent << "start_degree: ";
    Printer<double>::stream(s, indent + "  ", v.start_degree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SR_GRASP_MSGS_MESSAGE_FORCECONTROLGOAL_H
