// Generated by gencpp from file sr_grasp_msgs/KCL_GraspQualityQuery.msg
// DO NOT EDIT!


#ifndef SR_GRASP_MSGS_MESSAGE_KCL_GRASPQUALITYQUERY_H
#define SR_GRASP_MSGS_MESSAGE_KCL_GRASPQUALITYQUERY_H

#include <ros/service_traits.h>


#include <sr_grasp_msgs/KCL_GraspQualityQueryRequest.h>
#include <sr_grasp_msgs/KCL_GraspQualityQueryResponse.h>


namespace sr_grasp_msgs
{

struct KCL_GraspQualityQuery
{

typedef KCL_GraspQualityQueryRequest Request;
typedef KCL_GraspQualityQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KCL_GraspQualityQuery
} // namespace sr_grasp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQuery > {
  static const char* value()
  {
    return "b80430ef87f1ab2ffc18ffe08ba13cb0";
  }

  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQuery&) { return value(); }
};

template<>
struct DataType< ::sr_grasp_msgs::KCL_GraspQualityQuery > {
  static const char* value()
  {
    return "sr_grasp_msgs/KCL_GraspQualityQuery";
  }

  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQuery&) { return value(); }
};


// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQueryRequest> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQuery > 
template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQuery >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::KCL_GraspQualityQueryRequest> should match 
// service_traits::DataType< ::sr_grasp_msgs::KCL_GraspQualityQuery > 
template<>
struct DataType< ::sr_grasp_msgs::KCL_GraspQualityQueryRequest>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::KCL_GraspQualityQuery >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQueryResponse> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQuery > 
template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::KCL_GraspQualityQuery >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::KCL_GraspQualityQueryResponse> should match 
// service_traits::DataType< ::sr_grasp_msgs::KCL_GraspQualityQuery > 
template<>
struct DataType< ::sr_grasp_msgs::KCL_GraspQualityQueryResponse>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::KCL_GraspQualityQuery >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_GraspQualityQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_GRASP_MSGS_MESSAGE_KCL_GRASPQUALITYQUERY_H
