// Generated by gencpp from file sr_grasp_msgs/KCL_PoseCorrection.msg
// DO NOT EDIT!


#ifndef SR_GRASP_MSGS_MESSAGE_KCL_POSECORRECTION_H
#define SR_GRASP_MSGS_MESSAGE_KCL_POSECORRECTION_H

#include <ros/service_traits.h>


#include <sr_grasp_msgs/KCL_PoseCorrectionRequest.h>
#include <sr_grasp_msgs/KCL_PoseCorrectionResponse.h>


namespace sr_grasp_msgs
{

struct KCL_PoseCorrection
{

typedef KCL_PoseCorrectionRequest Request;
typedef KCL_PoseCorrectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KCL_PoseCorrection
} // namespace sr_grasp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrection > {
  static const char* value()
  {
    return "6f6f28b543f31ba5c3ddd26676eb9bb8";
  }

  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrection&) { return value(); }
};

template<>
struct DataType< ::sr_grasp_msgs::KCL_PoseCorrection > {
  static const char* value()
  {
    return "sr_grasp_msgs/KCL_PoseCorrection";
  }

  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrection&) { return value(); }
};


// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrectionRequest> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrection > 
template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrection >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::KCL_PoseCorrectionRequest> should match 
// service_traits::DataType< ::sr_grasp_msgs::KCL_PoseCorrection > 
template<>
struct DataType< ::sr_grasp_msgs::KCL_PoseCorrectionRequest>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::KCL_PoseCorrection >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrectionResponse> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrection > 
template<>
struct MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::KCL_PoseCorrection >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::KCL_PoseCorrectionResponse> should match 
// service_traits::DataType< ::sr_grasp_msgs::KCL_PoseCorrection > 
template<>
struct DataType< ::sr_grasp_msgs::KCL_PoseCorrectionResponse>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::KCL_PoseCorrection >::value();
  }
  static const char* value(const ::sr_grasp_msgs::KCL_PoseCorrectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_GRASP_MSGS_MESSAGE_KCL_POSECORRECTION_H
