// Generated by gencpp from file sr_grasp_msgs/PclFilter.msg
// DO NOT EDIT!


#ifndef SR_GRASP_MSGS_MESSAGE_PCLFILTER_H
#define SR_GRASP_MSGS_MESSAGE_PCLFILTER_H

#include <ros/service_traits.h>


#include <sr_grasp_msgs/PclFilterRequest.h>
#include <sr_grasp_msgs/PclFilterResponse.h>


namespace sr_grasp_msgs
{

struct PclFilter
{

typedef PclFilterRequest Request;
typedef PclFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PclFilter
} // namespace sr_grasp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_grasp_msgs::PclFilter > {
  static const char* value()
  {
    return "94a75bcf13eda1fa8daac70635072bbf";
  }

  static const char* value(const ::sr_grasp_msgs::PclFilter&) { return value(); }
};

template<>
struct DataType< ::sr_grasp_msgs::PclFilter > {
  static const char* value()
  {
    return "sr_grasp_msgs/PclFilter";
  }

  static const char* value(const ::sr_grasp_msgs::PclFilter&) { return value(); }
};


// service_traits::MD5Sum< ::sr_grasp_msgs::PclFilterRequest> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::PclFilter > 
template<>
struct MD5Sum< ::sr_grasp_msgs::PclFilterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::PclFilter >::value();
  }
  static const char* value(const ::sr_grasp_msgs::PclFilterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::PclFilterRequest> should match 
// service_traits::DataType< ::sr_grasp_msgs::PclFilter > 
template<>
struct DataType< ::sr_grasp_msgs::PclFilterRequest>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::PclFilter >::value();
  }
  static const char* value(const ::sr_grasp_msgs::PclFilterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_grasp_msgs::PclFilterResponse> should match 
// service_traits::MD5Sum< ::sr_grasp_msgs::PclFilter > 
template<>
struct MD5Sum< ::sr_grasp_msgs::PclFilterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_grasp_msgs::PclFilter >::value();
  }
  static const char* value(const ::sr_grasp_msgs::PclFilterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_grasp_msgs::PclFilterResponse> should match 
// service_traits::DataType< ::sr_grasp_msgs::PclFilter > 
template<>
struct DataType< ::sr_grasp_msgs::PclFilterResponse>
{
  static const char* value()
  {
    return DataType< ::sr_grasp_msgs::PclFilter >::value();
  }
  static const char* value(const ::sr_grasp_msgs::PclFilterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_GRASP_MSGS_MESSAGE_PCLFILTER_H
